//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM_TimeTracker.Ressources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BM_TimeTracker.Ressources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to Taskmanager ähnelt.
        /// </summary>
        internal static string admin_backtomanage {
            get {
                return ResourceManager.GetString("admin_backtomanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical days ähnelt.
        /// </summary>
        internal static string admin_criticaldays {
            get {
                return ResourceManager.GetString("admin_criticaldays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string admin_date {
            get {
                return ResourceManager.GetString("admin_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        internal static string admin_end {
            get {
                return ResourceManager.GetString("admin_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export as excel ähnelt.
        /// </summary>
        internal static string admin_export {
            get {
                return ResourceManager.GetString("admin_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal ähnelt.
        /// </summary>
        internal static string admin_intern {
            get {
                return ResourceManager.GetString("admin_intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load data ähnelt.
        /// </summary>
        internal static string admin_loaddata {
            get {
                return ResourceManager.GetString("admin_loaddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string admin_settings {
            get {
                return ResourceManager.GetString("admin_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string admin_start {
            get {
                return ResourceManager.GetString("admin_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ähnelt.
        /// </summary>
        internal static string admin_task {
            get {
                return ResourceManager.GetString("admin_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time in minutes ähnelt.
        /// </summary>
        internal static string admin_timeinminutes {
            get {
                return ResourceManager.GetString("admin_timeinminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: Admin ähnelt.
        /// </summary>
        internal static string admin_title {
            get {
                return ResourceManager.GetString("admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usermanagement ähnelt.
        /// </summary>
        internal static string admin_usermanage {
            get {
                return ResourceManager.GetString("admin_usermanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid time entered ähnelt.
        /// </summary>
        internal static string adminSettings_invalidTime {
            get {
                return ResourceManager.GetString("adminSettings_invalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum logged time ähnelt.
        /// </summary>
        internal static string adminSettings_minTime {
            get {
                return ResourceManager.GetString("adminSettings_minTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string adminSettings_save {
            get {
                return ResourceManager.GetString("adminSettings_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book it ähnelt.
        /// </summary>
        internal static string bookit_booktime {
            get {
                return ResourceManager.GetString("bookit_booktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate ähnelt.
        /// </summary>
        internal static string bookit_calculatetime {
            get {
                return ResourceManager.GetString("bookit_calculatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editing ähnelt.
        /// </summary>
        internal static string bookit_editing {
            get {
                return ResourceManager.GetString("bookit_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter taskname ähnelt.
        /// </summary>
        internal static string bookit_entertaskname {
            get {
                return ResourceManager.GetString("bookit_entertaskname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal ähnelt.
        /// </summary>
        internal static string bookit_intern {
            get {
                return ResourceManager.GetString("bookit_intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid time ähnelt.
        /// </summary>
        internal static string bookit_invalidtime {
            get {
                return ResourceManager.GetString("bookit_invalidtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string bookit_savetime {
            get {
                return ResourceManager.GetString("bookit_savetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ähnelt.
        /// </summary>
        internal static string bookit_task {
            get {
                return ResourceManager.GetString("bookit_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time minutes ähnelt.
        /// </summary>
        internal static string bookit_timeminutes {
            get {
                return ResourceManager.GetString("bookit_timeminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: Booking ähnelt.
        /// </summary>
        internal static string bookit_title {
            get {
                return ResourceManager.GetString("bookit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Values for
        ///password or user ähnelt.
        /// </summary>
        internal static string changeuser_invalidvalue {
            get {
                return ResourceManager.GetString("changeuser_invalidvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password ähnelt.
        /// </summary>
        internal static string changeuser_newpassword {
            get {
                return ResourceManager.GetString("changeuser_newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password ähnelt.
        /// </summary>
        internal static string changeuser_oldpassword {
            get {
                return ResourceManager.GetString("changeuser_oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwords must
        ///match ähnelt.
        /// </summary>
        internal static string changeuser_passwordmustmatch {
            get {
                return ResourceManager.GetString("changeuser_passwordmustmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reenter new password ähnelt.
        /// </summary>
        internal static string changeuser_reenternewpassword {
            get {
                return ResourceManager.GetString("changeuser_reenternewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string changeuser_save {
            get {
                return ResourceManager.GetString("changeuser_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: Change password ähnelt.
        /// </summary>
        internal static string changeuser_title {
            get {
                return ResourceManager.GetString("changeuser_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong password ähnelt.
        /// </summary>
        internal static string changeuser_wrongpassword {
            get {
                return ResourceManager.GetString("changeuser_wrongpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something horrible went wrong ähnelt.
        /// </summary>
        internal static string global_horribleException {
            get {
                return ResourceManager.GetString("global_horribleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string global_time {
            get {
                return ResourceManager.GetString("global_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        internal static string global_user {
            get {
                return ResourceManager.GetString("global_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password and/or username ähnelt.
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New User ähnelt.
        /// </summary>
        internal static string login_newuser {
            get {
                return ResourceManager.GetString("login_newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin ähnelt.
        /// </summary>
        internal static string manage_admin {
            get {
                return ResourceManager.GetString("manage_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task is finished ähnelt.
        /// </summary>
        internal static string manage_alreadyfinished {
            get {
                return ResourceManager.GetString("manage_alreadyfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Task already running ähnelt.
        /// </summary>
        internal static string manage_alreadyrunning {
            get {
                return ResourceManager.GetString("manage_alreadyrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book it ähnelt.
        /// </summary>
        internal static string manage_bookit {
            get {
                return ResourceManager.GetString("manage_bookit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change password ähnelt.
        /// </summary>
        internal static string manage_changepassword {
            get {
                return ResourceManager.GetString("manage_changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Critical days ähnelt.
        /// </summary>
        internal static string manage_criticaldays {
            get {
                return ResourceManager.GetString("manage_criticaldays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string manage_date {
            get {
                return ResourceManager.GetString("manage_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string manage_delete {
            get {
                return ResourceManager.GetString("manage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string manage_edit {
            get {
                return ResourceManager.GetString("manage_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In progress ähnelt.
        /// </summary>
        internal static string manage_inediting {
            get {
                return ResourceManager.GetString("manage_inediting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internal ähnelt.
        /// </summary>
        internal static string manage_intern {
            get {
                return ResourceManager.GetString("manage_intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string manage_logut {
            get {
                return ResourceManager.GetString("manage_logut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only active tasks ähnelt.
        /// </summary>
        internal static string manage_onlyactive {
            get {
                return ResourceManager.GetString("manage_onlyactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string manage_pause {
            get {
                return ResourceManager.GetString("manage_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string manage_start {
            get {
                return ResourceManager.GetString("manage_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Task ähnelt.
        /// </summary>
        internal static string manage_startTask {
            get {
                return ResourceManager.GetString("manage_startTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string manage_startTaskButton {
            get {
                return ResourceManager.GetString("manage_startTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ähnelt.
        /// </summary>
        internal static string manage_task {
            get {
                return ResourceManager.GetString("manage_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time in minutes ähnelt.
        /// </summary>
        internal static string manage_timeminutes {
            get {
                return ResourceManager.GetString("manage_timeminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: Taskmanagement ähnelt.
        /// </summary>
        internal static string manage_title {
            get {
                return ResourceManager.GetString("manage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logged in as: ähnelt.
        /// </summary>
        internal static string manage_username {
            get {
                return ResourceManager.GetString("manage_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        internal static string manange_pauseTaskButton {
            get {
                return ResourceManager.GetString("manange_pauseTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string newuser_password {
            get {
                return ResourceManager.GetString("newuser_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your passwords must match ähnelt.
        /// </summary>
        internal static string newuser_passwordmustmatch {
            get {
                return ResourceManager.GetString("newuser_passwordmustmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your password ähnelt.
        /// </summary>
        internal static string newuser_pleaseenterpassword {
            get {
                return ResourceManager.GetString("newuser_pleaseenterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your username ähnelt.
        /// </summary>
        internal static string newuser_pleaseenterusername {
            get {
                return ResourceManager.GetString("newuser_pleaseenterusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reenter your password ähnelt.
        /// </summary>
        internal static string newuser_reenterpassword {
            get {
                return ResourceManager.GetString("newuser_reenterpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string newuser_save {
            get {
                return ResourceManager.GetString("newuser_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: New User ähnelt.
        /// </summary>
        internal static string newuser_title {
            get {
                return ResourceManager.GetString("newuser_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username already taken ähnelt.
        /// </summary>
        internal static string newuser_useralreadytaken {
            get {
                return ResourceManager.GetString("newuser_useralreadytaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string newuser_username {
            get {
                return ResourceManager.GetString("newuser_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book task ähnelt.
        /// </summary>
        internal static string tray_bookit {
            get {
                return ResourceManager.GetString("tray_bookit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string tray_exit {
            get {
                return ResourceManager.GetString("tray_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New task ähnelt.
        /// </summary>
        internal static string tray_newtask {
            get {
                return ResourceManager.GetString("tray_newtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause task ähnelt.
        /// </summary>
        internal static string tray_pause {
            get {
                return ResourceManager.GetString("tray_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start task ähnelt.
        /// </summary>
        internal static string tray_start {
            get {
                return ResourceManager.GetString("tray_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User is admin ähnelt.
        /// </summary>
        internal static string usermanage_adminCheckBox {
            get {
                return ResourceManager.GetString("usermanage_adminCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t delete the last User ähnelt.
        /// </summary>
        internal static string usermanage_cannotDeleteLastUser {
            get {
                return ResourceManager.GetString("usermanage_cannotDeleteLastUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot delete yourself ähnelt.
        /// </summary>
        internal static string usermanage_cannotDeleteSelf {
            get {
                return ResourceManager.GetString("usermanage_cannotDeleteSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t override adminrights
        ///on admin
        /// ähnelt.
        /// </summary>
        internal static string usermanage_cannotOverrideAdmin {
            get {
                return ResourceManager.GetString("usermanage_cannotOverrideAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comfirm deletion ähnelt.
        /// </summary>
        internal static string usermanage_confirmdelete {
            get {
                return ResourceManager.GetString("usermanage_confirmdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string usermanage_delete {
            get {
                return ResourceManager.GetString("usermanage_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete this user? ähnelt.
        /// </summary>
        internal static string usermanage_doyouwanttodeleteuser {
            get {
                return ResourceManager.GetString("usermanage_doyouwanttodeleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new user ähnelt.
        /// </summary>
        internal static string usermanage_newuser {
            get {
                return ResourceManager.GetString("usermanage_newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string usermanage_password {
            get {
                return ResourceManager.GetString("usermanage_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password too short ähnelt.
        /// </summary>
        internal static string usermanage_passwordtooshort {
            get {
                return ResourceManager.GetString("usermanage_passwordtooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string usermanage_save {
            get {
                return ResourceManager.GetString("usermanage_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving successful ähnelt.
        /// </summary>
        internal static string usermanage_savesuccess {
            get {
                return ResourceManager.GetString("usermanage_savesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeTracker: Usermanagement ähnelt.
        /// </summary>
        internal static string usermanage_title {
            get {
                return ResourceManager.GetString("usermanage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User already exists ähnelt.
        /// </summary>
        internal static string usermanage_useralreadyexists {
            get {
                return ResourceManager.GetString("usermanage_useralreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string usermanage_username {
            get {
                return ResourceManager.GetString("usermanage_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username too short ähnelt.
        /// </summary>
        internal static string usermanage_usernametooshort {
            get {
                return ResourceManager.GetString("usermanage_usernametooshort", resourceCulture);
            }
        }
    }
}
